CREATE DATABASE IF NOT EXISTS `tests` ;

CREATE TABLE IF NOT EXISTS `users` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `username` VARCHAR (50) NOT NULL,
  `email` VARCHAR (50) NOT NULL,
  `password` VARCHAR (255) NOT NULL,
  PRIMARY KEY (`id`),
  FULLTEXT INDEX (`username`),
  FULLTEXT INDEX (`email`),
  UNIQUE INDEX (`password`)
) ENGINE = INNODB CHARSET = utf8mb4 COLLATE = utf8mb4_general_ci ;
